---
deployment:
  tasks:
    - export DEPLOYPATH=/home/supplfsj/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH