INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Aboutus', 'index', 'About us', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Aboutus', 'save', 'Update About us', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Activity', 'index', 'Activity list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Activity', 'get_records', 'Activity list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Associated_brands', 'index', 'Associated Brands', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Associated_brands', 'get_dtrecords', 'Associated Brands', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Associated_brands', 'read', ' Associated Brands View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Associated_brands', 'create', 'Associated Brands Add ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Associated_brands', 'create_action', 'Associated Brands Add ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Associated_brands', 'update', 'Associated Brands Edit', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Associated_brands', 'update_action', 'Associated Brands Edit', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Associated_brands', 'delete', 'Associated Brands Delete', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');


INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'index', 'Attribute', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'sort', 'Attribute Sort', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'save_attribute_order', 'Attribute orders', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'get_attributes', 'Attribute List', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'create', 'Attribute Add', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'create_action', 'Attribute Add Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'update', 'Attribute Edit', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'update_action', 'Attribute Edit Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'delete', 'Attribute Delete', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'getAttributesDetails', 'Attribute details', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Attribute', 'get_dtrecords', 'Attribute List', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'index', 'Blogs', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'read', 'Blogs View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'create', 'Blogs Add', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'create_action', 'Blogs Add Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'update', 'Blogs Edit', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'update_action', 'Blogs Edit Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'delete', 'Blogs Delete ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'publish', 'Blogs Publish ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Blogs', 'get_records', 'Blogs list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Category', 'index', 'Category', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Category', 'read', 'Category View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Category', 'create', 'Category Add ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Category', 'create_action', 'Category Add Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Category', 'update', 'Category Edit', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Category', 'update_action', 'Category Edit Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Category', 'delete', 'Category Delete', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Category', 'get_dtrecords', 'Category list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'index', 'Customers', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'read', 'Customers View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'create', 'Customers Add', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'create_action', 'Customers Add Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'update', 'Customers Edit ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'update_action', 'Customers Edit Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'delete', 'Customers Delete ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'get_dtrecords', 'Customers list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'report', 'Customers report', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Customers', 'get_dtrecords_customer_report', 'Customers report', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Downloads', 'index', 'Downloads', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Downloads', 'save', 'Downloads Add', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Downloads', 'delete', 'Downloads Delete', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Downloads', 'get_dtrecords', 'Downloads list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Enquires', 'index', 'Enquires', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Enquires', 'enquiry_details', 'Enquires View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Enquires', 'get_dtrecords', 'Enquires list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Home_page_slider', 'index', 'Home_page_slider', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Home_page_slider', 'read', 'Home_page_slider View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Home_page_slider', 'create', 'Home_page_slider Add ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Home_page_slider', 'create_action', 'Home_page_slider Add Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Home_page_slider', 'update', 'Home_page_slider Edit ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Home_page_slider', 'update_action', 'Home_page_slider Edit Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Home_page_slider', 'delete', 'Home_page_slider Delete ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Home_page_slider', 'get_records', 'Home_page_slider list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');


INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Message', 'index', 'Message', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Message', 'read', 'Message View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Message', 'create', 'Message Add ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Message', 'create_action', 'Message Add Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Message', 'get_custnames', 'Customers list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Message', 'get_dtrecords', 'Message list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'index', 'Products', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'read', 'Products View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'create', 'Products Add', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'create_action', 'Products Add Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'update', 'Products Edit', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'update_action', 'Products Edit Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'delete', 'Products Delete ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'get_dtrecords', 'Products list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'get_product_tax_rate', 'Products Get Tax rate', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Products', 'get_sub_category', 'Products get sub category', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Proforma_invoice', 'index', 'Proforma invoice', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Proforma_invoice', 'send_pi_to_customer', 'proforma invoice send to customer', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Proforma_invoice', 'view', 'Proforma invoice View ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Proforma_invoice', 'create_action', 'Proforma invoice Add ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Proforma_invoice', 'upload_proforma_invoice', 'Proforma invoice Upload ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Proforma_invoice', 'get_dtrecords', 'Proforma invoice list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');


INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'index', 'Purchase_orders', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'cancel_purchase_order', 'Purchase_orders Cancel', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'view', 'Purchase_orders View ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'send_po_to_supplier', ' Purchase_orders send to supplier', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'purchase_order_to_supplier_action', 'purchase_order_to_supplier_action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'purchase_order_to_supplier_view', 'purchase_order_to_supplier_view', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'purchase_order_to_supplier_list', 'purchase_order_to_supplier_list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'get_dtrecords', 'purchase order list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'get_supdtrecords', 'supplier purchase order list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'get_suppliernames', 'supplier names', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'purchase_order_to_warehouse_list', 'purchase_order_to_warehouse_list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'get_dtrecords_purchase_order_to_warehouse', 'get_dtrecords_purchase_order_to_warehouse', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'send_to_warehouse', 'send_to_warehouse', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'send_to_warehouse_action', 'send_to_warehouse_action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Purchase_orders', 'purchase_order_to_warehouse_view', 'purchase_order_to_warehouse_view', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'index', 'Quotation', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'send_quotation', 'Quotation send ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'view_quotation', 'Quotation View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'create_action', 'Quotation Create', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'send_quotation_to_customer', 'Quotation send to customer', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'update', 'Quotation Update', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'update_action', 'Qotation Update Action', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'delete', 'Quotation delete', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Quotation', 'get_dtrecords', 'Quotation list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');


INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Testimonials', 'index', 'Testimonials', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Testimonials', 'read', 'Testimonials View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Testimonials', 'update', 'Testimonials Edit ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Testimonials', 'update_action', 'Testimonials Update ', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Testimonials', 'activate', 'Testimonials Activatation', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Testimonials', 'get_dtrecords', 'Testimonials list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');

INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Transporters', 'index', 'Transporters', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Transporters', 'read', 'Transporters View', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Transporters', 'create', 'Transporters Add', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Transporters', 'create_action', 'Transporters Add', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Transporters', 'update', 'Transporters Edit', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Transporters', 'update_action', 'Transporters Update', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Transporters', 'delete', 'Transporters Delete', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
INSERT INTO `rights` (`rights_id`, `controller_name`, `method_name`, `display_name`, `created_at`, `updated_at`, `status`) VALUES (NULL, 'Transporters', 'get_dtrecords', 'Transporters list', CURRENT_TIMESTAMP, '0000-00-00 00:00:00.000000', '1');
